### ISSUE TITLE
Homer and repeat data in SourceData

### ISSUE THREAD

**Issue by YFan1997** [Zhong-Lab-UCSD/RNA3Dgenome-code-repository#2]
Dear authors, 

Thank you for providing these codes and guideline, I was trying to regenerate the code and figures of IMARGI, during my learning process, I have a quick question about using HOMER to find rectangular blocks. my process is: get the bedpe file, then extract the first three columns and convert to bed (chrom1, start1, end1), and findPeaks (-style histone -size 5000 -minDist 12000), based on this RNA peak result, filter the chrom2, start2, end2 in the range of RNA peaks, again apply findPeaks (-style histone -size 25000 -minDist 50000). Would this process correct? I got 2461 peaks based on 4DNFIZZLJKSX.pair.gz

Another question that I have is in SourceData file, the Figure_1a_cRAL.tsv is same with Figure_1a_RAL.tsv. aslo for Figure_1b_cRAL and Figure_1b_RAL.  

Based on my understanding, the cRAL is calculated by each DNA end bins, while the RAL of specific gene is extract the corresponding RNA position first and then calculate the RAL for each DNA end bins?

Thank you in advance for your time and response.

Best,
Yifan

**Comment by qizhijie** [comment]
Hi, Yifan,

Regarding your rectangular block question, you are generally correct about the process. For our analysis applying findPeaks, the '-style' option was not used. The other parameters to be added are '-F 0    -P 1    -L 0    -LP 1    -C 0    -fdr 1    -tagThreshold 1    -ntagThreshold 1'.

**Comment by rcalandrelli** [comment]
Hi Yifan,

Thanks for pointing this out. Your understanding about cRAL and RAL is correct.

I noticed an error in the code to generate the source data files which was producing the same output files, apologies about that. I have attached the updated versions of cRAL for both Figure 1a and 1b (the RAL files are fine). Hope this helps!

[Figure_1b_cRAL.txt](https://github.com/user-attachments/files/15706993/Figure_1b_cRAL.txt)
[Figure_1a_cRAL.txt](https://github.com/user-attachments/files/15707001/Figure_1a_cRAL.txt)

**Comment by YFan1997** [comment]
Thank you for these information and clarifications! 

Best,
Yifan
